### PR TITLE
Develop has first draft of family tree

### PR DESCRIPTION
**Pull request by r4sNorby**

### CODE REVIEW

**Comment by r4sNorby** [comment]
This is good

**Review by ealbrechtsen — COMMENTED** [review]
decent

**Review by Naywia — APPROVED** [review]
👌

**Review by mrpink32 — APPROVED** [review]
This is probably the greatest code to ever be gazed upon

**Review by ealbrechtsen — APPROVED** [review]
Decent enough to approve

**Review by DSmaSSen — APPROVED** [review]
apwruft

**Pull request merged**
